spring:
  application.name: Migration1

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: westside

  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
  flyway:
    enabled: true                # ????????? Flyway
    schemas: migration_test      #??????? ????? ???? ????? ??????????? ??????? ???? ?? ????? ??????? ?????? ????? ?? ???????

