spring:
  application.name: Migration1

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: westside

  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
  flyway:
    enabled: true                # activate Flyway
    schemas: migration_test      # if we don't want to clear our db we create new scheme and attach it to flyway
    locations: classpath:db/migration

